### ISSUE TITLE
当主机禁icmp的时候无法获取ip

### ISSUE THREAD

**Issue by DawnLiExp** [lixuy/CloudXNS-DDNS-with-BashShell#2]
提示本地DNS域名记录错误。

虽然禁ping，也能返回ip的，应该可以根据返回值来操作更科学点。

**Comment by kkkgo** [comment]
你好，脚本采用正则匹配ip地址，禁ping不影响获取ip。

**Comment by DawnLiExp** [comment]
在手头亚马逊aws d8 d9系统下，禁ping后就会这样：

```
[URL IP]:a.a.a.a
[DNS IP]:Get aa.domain.com DNS Failed.
API UPDATE DDNS SUCCESS a.a.a.a
```

允许icmp后就正常。特意用阿里云的试了下无此问题，系统优化设置什么的都一样，除了镜像是用各主机商自己的。

PS：[issue-386544977](https://github.com/lixuy/CloudXNS-DDNS-with-BashShell/issues/3#issue-386544977)，已经解决，就不去打开issue了。

没有用 http://ip.qq.com ，我也发觉失效，用的是 http://ipinfo.io/ip ，应该是curl -4解决了D9下卡住的问题。

**Comment by kkkgo** [comment]
把这段代码保存为脚本执行看看
```shell
. /etc/profile
DOMAIN="icmp.03k.org"
IPREX='([0-9]{1,2}|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.([0-9]{1,2}|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.([0-9]{1,2}|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.([0-9]{1,2}|1[0-9][0-9]|2[0-4][0-9]|25[0-5])'
dnscmd="nslookup";type nslookup >/dev/null 2>&1||dnscmd="ping -c1"
echo dnscmd_is_$dnscmd
DNSTEST=$($dnscmd $DOMAIN)
echo cmd_result:
$dnscmd $DOMAIN
DNSIP=$(echo $DNSTEST|grep -Eo "$IPREX"|tail -n1)
echo grep_result:
echo $DNSTEST|grep -Eo "$IPREX"|tail -n1
echo final_result:
echo ip_$DNSIP

```

**Comment by DawnLiExp** [comment]
返回：

> dnscmd_is_ping -c1
> cmd_result:
> PING icmp.03k.org (111.22.33.254) 56(84) bytes of data.
> 
> --- icmp.03k.org ping statistics ---
> 1 packets transmitted, 0 received, 100% packet loss, time 0ms
> 
> grep_result:
> 111.22.33.254
> final_result:
> ip_111.22.33.254

**Comment by kkkgo** [comment]
看起来能正常获取ip呀，那你把DOMAIN换成你的域名看看？

**Comment by kkkgo** [comment]
我怀疑问题不是出在ping上，稍等我发另一个脚本

**Comment by DawnLiExp** [comment]
换自己的域名返回值也一样。

改了下解析，用ddns脚本还是：
```
[URL IP]:a.a.a.a
[DNS IP]:Get aa.domain.com DNS Failed.
API UPDATE DDNS SUCCESS a.a.a.a
```
但发觉是真的UPDATE SUCCESS了，我猜这样可能会按照cron的时间不停的修改。
允许ping以后才会提示SKIP UPDATE。

ps：回复很及时，感谢。这个问题不大，允许ping先，你有空闲再看。

**Comment by kkkgo** [comment]
使用新脚本尝试下

**Comment by DawnLiExp** [comment]
辛苦，问题解决，👍🏻
