### ISSUE TITLE
更新解析失败

### ISSUE THREAD

**Issue by DawnLiExp** [lixuy/CloudXNS-DDNS-with-BashShell#3]
主机商aws
debian9 64
手动执行脚本cloudxns_ddns.sh
域名用的是s1 s2 s3.domain.com这种模式
同样设置在aws debian 8 下正常

API未设置白名单，ip未变的时候能正常提示：
[URL IP]:a.a.a.a
[DNS IP]:a.a.a.a
IP SAME IN DNS,SKIP UPDATE.

但如果主机与解析IP不同，会卡在：
[URL IP]:a.a.a.a
[DNS IP]:b.b.b.b
这一步没有其它提示。

**Comment by kkkgo** [comment]
ip.qq.com倒闭了，稍后我更新下脚本

**Comment by kkkgo** [comment]
脚本已经更新，请测试，如有报错请再次打开此issue，谢谢！
